"""
Named presentation constants shared across the Pygame UI.
"""

from pathlib import Path

BOARD_PIXEL_SIZE = 512
BOARD_DIMENSION = 8
SQUARE_SIZE = BOARD_PIXEL_SIZE // BOARD_DIMENSION

PIECE_IMAGE_DIRECTORY = Path(__file__).resolve().parent.parent / 'assets' / 'images' / 'chess_pieces'

MOVE_ANIMATION_DURATION_MS = 200
GAME_OVER_DELAY_MS = 3000
ENDGAME_FLASH_CYCLE_MS = 1000
ENDGAME_SQUARE_MAX_OPACITY = 0.75
ENDGAME_TEXT_MIN_OPACITY = 0.15
ENDGAME_TEXT_MAX_OPACITY = 0.90

MODAL_OVERLAY_ALPHA = 210
PROMOTION_OVERLAY_ALPHA = 180

BUTTON_BORDER_WIDTH = 2
BUTTON_CORNER_RADIUS = 8

STATUS_FONT_SIZE = 58
RESULT_FONT_SIZE = 48
TITLE_FONT_SIZE = 44
BUTTON_FONT_SIZE = 30

RESULT_BUTTON_WIDTH = 220
RESULT_BUTTON_HEIGHT = 50
RESULT_BUTTON_GAP = 15
RESULT_TO_BUTTON_GAP = 28

GAMEMODE_PANEL_WIDTH = 300
GAMEMODE_BUTTON_HEIGHT = 46
GAMEMODE_BUTTON_GAP = 12
GAMEMODE_ACTION_HEIGHT = 50
GAMEMODE_ACTION_GAP = 10
GAMEMODE_TITLE_GAP = 20
GAMEMODE_ACTIONS_TOP_GAP = 22
GAMEMODE_BACK_WIDTH_RATIO = 0.30

PROMOTION_PIECES = ('Q', 'R', 'B', 'N')
PROMOTION_BUTTON_GAP_RATIO = 1 / 3

BOARD_LIGHT_COLOR = 'white'
BOARD_DARK_COLOR = 'gray'
TEXT_COLOR = 'white'
TEXT_SHADOW_COLOR = 'black'
ENDGAME_TEXT_COLOR = '#FF4040'
MODAL_OVERLAY_COLOR = (10, 10, 10)
ENDGAME_SQUARE_COLOR = (255, 0, 0)
BUTTON_DEFAULT_COLOR = '#26A867'
BUTTON_HOVER_COLOR = '#51A57B'
BUTTON_SELECTED_COLOR = '#D49B2E'
BUTTON_SELECTED_BORDER_COLOR = '#FFE29A'
PROMOTION_BUTTON_COLOR = 'white'
PROMOTION_BUTTON_HOVER_COLOR = 'lightgray'
PROMOTION_BUTTON_BORDER_COLOR = 'black'
TEXT_SHADOW_OFFSET = 3
FULL_ALPHA = 255
HOVER_COLOR = (153, 255, 102)
HOVER_ALPHA = 70
SELECTED_COLOR = (0, 180, 255)
SELECTED_ALPHA = 130
LEGAL_MOVE_COLOR = (0, 200, 255)
LEGAL_MOVE_ALPHA = 110
CAPTURE_COLOR = (255, 40, 40)
CAPTURE_ALPHA = 130
CHECK_COLOR = (255, 0, 0)
CHECK_ALPHA = 150
