"""
Application loop configuration.
"""

MAX_FPS = 60

MATCH_HISTORY_FOLDER_NAME = 'match_history'
MATCH_HISTORY_TIMESTAMP_FORMAT = '%Y%m%d-%H%M'
MATCH_HISTORY_FILE_EXTENSION = '.txt'

MATCH_HISTORY_SEPARATOR_CHARACTER = '='
MATCH_HISTORY_SEPARATOR_LENGTH = 51
MATCH_HISTORY_SEPARATOR_LINES = 3
